#!/usr/bin/env bash
make clean
make ENABLE_MULTITHREAD="" dlls
rm -rf dll32
mkdir dll32
mv *.dll dll32/

export PATH=/MinGW64/mingw-w64-1.0-bin_i686-mingw_20100702/bin:$PATH
export C_INCLUDE_PATH=/MinGW64/mingw-w64-1.0-bin_i686-mingw_20100702/include
export LIBRARY_PATH=/MinGW64/mingw-w64-1.0-bin_i686-mingw_20100702/lib
make clean
make ENABLE_MULTITHREAD="" dlls
rm -rf dll64
mkdir dll64
mv *.dll dll64/
